<!DOCTYPE html>
<html lang="en" class="no-js"> 
    <head> 
        <meta charset="utf-8" />
        <link rel="stylesheet" href="<?=$vars['baseUrl']?>/report_detail_screen.css" type="text/css" media="screen" charset="utf-8"/>
        <link rel="stylesheet" href="<?=$vars['baseUrl']?>/report_detail.css" type="text/css" media="screen" charset="utf-8"/>
        <link rel="stylesheet" href="<?=$vars['baseUrl']?>/report_detail_print.css" type="text/css" media="screen" charset="utf-8"/>
        <title>ZReport</title>
    </head>
    <body>
        <ul class="report combineChildItems">